steps:
  - label: "🤡 :hammer:"
    plugins:
      - plugin-tester#v1.1.1: ~

  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: detect-clowns

  - label: ":shell: Shellcheck"    
    plugins:
      - shellcheck#v1.3.0:
          files: hooks/**
